// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCim67g_pDHxw-QapxL08HIYrqGaZD5Qx8',
    appId: '1:669993496829:web:908c7da308726a88534e94',
    messagingSenderId: '669993496829',
    projectId: 'flutter-login-app-e4df0',
    authDomain: 'flutter-login-app-e4df0.firebaseapp.com',
    storageBucket: 'flutter-login-app-e4df0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlyQD7eWOq76Q3Bo-wCBAkaej4hPTbWu4',
    appId: '1:669993496829:android:c5d20a68e15dbfdf534e94',
    messagingSenderId: '669993496829',
    projectId: 'flutter-login-app-e4df0',
    storageBucket: 'flutter-login-app-e4df0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIinPtcwWK_A5xEUmlajqnXr-B56kKq3U',
    appId: '1:669993496829:ios:c34347f6170d3248534e94',
    messagingSenderId: '669993496829',
    projectId: 'flutter-login-app-e4df0',
    storageBucket: 'flutter-login-app-e4df0.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIinPtcwWK_A5xEUmlajqnXr-B56kKq3U',
    appId: '1:669993496829:ios:c34347f6170d3248534e94',
    messagingSenderId: '669993496829',
    projectId: 'flutter-login-app-e4df0',
    storageBucket: 'flutter-login-app-e4df0.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCim67g_pDHxw-QapxL08HIYrqGaZD5Qx8',
    appId: '1:669993496829:web:42466349c192f0ef534e94',
    messagingSenderId: '669993496829',
    projectId: 'flutter-login-app-e4df0',
    authDomain: 'flutter-login-app-e4df0.firebaseapp.com',
    storageBucket: 'flutter-login-app-e4df0.appspot.com',
  );

}